window.OX_DATA = {
  imageBase: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/',
  images: {
    exterior: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092029/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-jpeg.webp',
    food: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092033/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-1-jpeg.webp',
    room: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092035/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-2-jpeg.webp',
    steak: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092039/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-3-jpeg.webp',
    table: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092041/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-4-jpeg.webp',
    patio: 'https://pub-5bcc3edf34304d04b59dc91e1ad9d2fd.r2.dev/nigeria.tortoisepath.com/uploads/2024/04/13092045/OX-Restaurant-Lounge-Lagos-Nigeria-TortoisePathcom-5-jpeg.webp'
  },
  contact: {
    phone: '+234 904 444 4454',
    whatsapp: '2349044444454',
    address: '31 Kofo Abayomi St, Victoria Island, Lagos, Nigeria',
    hours: { 'Mon–Sat': '15:00 — 02:00', 'Sunday': '12:00 — 02:00' },
    instagram: 'https://www.instagram.com/oxrestolounge/'
  },
  foodMenu: [
    {category:'Appetizers',name:'Corn on the Cup',price:11200,description:'Fresh fried corn sticks served with sriracha mayo dip.'},
    {category:'Appetizers',name:'Edamame',price:14200,description:'Steamed edamame pods lightly seasoned with Himalayan salt for a simple and flavorful bite.'},
    {category:'Appetizers',name:'Chicken Wings',price:16200,description:'Seasoned chicken wings served with BBQ or chili sauce.'},
    {category:'Appetizers',name:'Beef Bao',price:26400,description:'Smoked shredded beef, pickles & our special sauce.'},
    {category:'Appetizers',name:'Mini Burgers',price:22400,description:'3 premium beef burgers.'},
    {category:'Appetizers',name:'Beef Mini Tacos',price:19800,description:'Crisp mini corn tortillas filled with seasoned minced beef, creamy avocado mousse, fresh iceberg lettuce, a hint of Caribbean sauce, and spring onions.',tag:'NEW'},
    {category:'Appetizers',name:'Taco Chicken',price:18200,description:'Marinated chicken, avocado, fried onions & iceberg.'},
    {category:'Appetizers',name:'Pork Roll',price:24000,description:'Tender slow-cooked pork, marinated in signature barbecue sauce and rolled.'},
    {category:'Appetizers',name:'Dynamite Shrimp',price:17200,description:'Crispy fried shrimp coated in spicy mayonnaise dressing.'},
    {category:'Appetizers',name:'Shrimp Spring Rolls',price:17200,description:'Marinated shrimp wrapped and fried in crispy rolls.'},
    {category:'Appetizers',name:'Shrimp Roll',price:17800,description:'Nori paper, halloumi cheese & avocado with mayo punzo sauce.'},
    {category:'Appetizers',name:'Fried Calamari',price:18200,description:'Deep-fried calamari rings served with togarachi sauce.'},
    {category:'Appetizers',name:'Crispy Crab',price:17800,description:'Marinated fried crab with vegetables & spices, sweet chili mayo.'},
    {category:'Appetizers',name:'Suya (Beef/Shrimp/Chicken)',price:16200,description:'Coated with suya pepper served with tomato and onions.'},
    {category:'Appetizers',name:'Appetizers Platter',price:44200,description:'Assorted spring rolls, chicken tender, wings, cheddar beef bacon & panzerotti.'},
    {category:'Appetizers',name:'Seafood Platter',price:46200,description:'Fried calamari, shrimp rolls, grilled mussels & prawns suya.'},
    {category:'Appetizers',name:'Nigerian Platter',price:40200,description:'Spicy gizzards & snails, chicken suya, yam fingers & plantain.'},
    {category:'Salads',name:'Caesar Salad Chicken',price:21400,description:'Iceberg, parmesan, garlic croutons in Caesar sauce.'},
    {category:'Salads',name:'Caesar Salad Prawn',price:24200,description:'Iceberg, parmesan, garlic croutons in Caesar sauce.'},
    {category:'Salads',name:'Quinoa Power Salad',price:18400,description:'Quinoa, feta, edamame, cranberries, strawberries, avocado, wine dressing.'},
    {category:'Salads',name:'Kale Chicken Salad',price:22400,description:'Kale, almonds, cranberries, sesame seeds, grilled chicken, balsamic dressing.'},
    {category:'Salads',name:'Salmon Salad',price:26400,description:'Rocket, mesclun, cherry tomato, edamame, walnuts, radish, avocado, mango.'},
    {category:'Salads',name:'Cobb Salad',price:24400,description:'Iceberg, avocado, tomato, cucumber, chicken tenders, ranch.'},
    {category:'Burgers & Sandwiches',name:'Bacon Heat Burger',price:26200,description:'Juicy beef patty layered with cheddar cheese, caramelized onions, fresh mushrooms, rocket leaves, and signature bacon sauce on toasted bun.',tag:'NEW'},
    {category:'Burgers & Sandwiches',name:'OX Burger',price:27200,description:'Wagyu beef with cheddar, beef bacon, lettuce, tomato, pickles & caramelized onion.'},
    {category:'Burgers & Sandwiches',name:'Smashed Burger',price:25200,description:'Premium double smashed beef with cheddar, lettuce, caramelized onion, smashed sauce.'},
    {category:'Burgers & Sandwiches',name:'Chicken Suya Burger',price:24200,description:'Chicken breast coated with suya pepper with chipotle sauce.'},
    {category:'Burgers & Sandwiches',name:'Chicken Katsu Sandwich',price:22200,description:'Marinated chicken, Asian slaw, pickles, teriyaki mayo sauce. Served with fries.'},
    {category:'Burgers & Sandwiches',name:'Mini Shawarma Delight',price:22200,description:'Marinated chicken grilled and wrapped in pita with toppings. Served with fries.'},
    {category:'Burgers & Sandwiches',name:'Club Sandwich',price:22200,description:'Chicken, mustard mayo, cheddar, egg, beef bacon, lettuce, tomato & pickles.'},
    {category:'Burgers & Sandwiches',name:'Philadelphia Sandwich',price:27400,description:'Char-grilled BBQ beef with bell pepper, onions, mushroom & steak sauce.'},
    {category:'Pasta',name:'Truffle Mushroom Ravioli',price:23400,description:'Ravioli stuffed with mushroom and truffle paste in pink sauce.'},
    {category:'Pasta',name:'Tagliatelle Alfredo',price:26600,description:'Homemade tagliatelle pasta tossed in a rich, creamy mushroom sauce with tender chicken and finished with Parmesan cheese.'},
    {category:'Pasta',name:'Spaghetti Bolognaise',price:25600,description:'Spaghetti with homemade bolognaise sauce, tomato, basil & parmesan.'},
    {category:'Pasta',name:'Shrimp Linguini',price:29600,description:'Homemade linguine served with a flavorful tomato and bisque sauce, sautéed shrimp, cherry tomatoes, fresh basil, and Parmesan.'},
    {category:'Pasta',name:'Seafood Pasta',price:32800,description:'Homemade linguine combined with prawns, calamari, and mussels in a classic tomato sauce, finished with fresh basil and Parmesan.'},
    {category:'Pasta',name:'Oxtail Rigatoni',price:48200,description:'Slow-cooked oxtail and rigatoni pasta in a rich tomato sauce, topped with Parmesan cheese.',tag:'NEW'},
    {category:'Nigerian Delight',name:'Grilled Croaker Fish',price:34800,description:'Grilled croaker fish with chili sauce & fried yam.'},
    {category:'Nigerian Delight',name:'Half Roasted Chicken',price:34800,description:'Half roasted chicken with vegetables, jollof rice & chili sauce.'},
    {category:'Nigerian Delight',name:'Yam Finger',price:11200,description:'Deep fried yam served with tomato chili sauce.'},
    {category:'Nigerian Delight',name:'Goat Pepper Soup',price:16800,description:'Traditional spicy goat soup.'},
    {category:'Nigerian Delight',name:'Fish Pepper Soup',price:16800,description:'Traditional spicy fish soup.'},
    {category:'Nigerian Delight',name:'Asun',price:15800,description:'Goat meat with sauteed pepper, onions & tomato chili sauce.'},
    {category:'Nigerian Delight',name:'Egusi Soup',price:22400,description:'Beef, kpomo, stockfish, shaki & vegetables with pounded yam or semo.'},
    {category:'Nigerian Delight',name:'Seafood Okra',price:29200,description:'Croaker fish, okra, snails, shrimps, prawns & vegetables.'},
    {category:'Nigerian Delight',name:'Peppered Gizzards',price:15800,description:'Steamed gizzards with pepper, onions & chili sauce.'},
    {category:'Nigerian Delight',name:'Peppered Snails',price:19800,description:'Steamed snails with onions, green pepper & chili sauce.'},
    {category:'Main Course',name:'Char-Grilled Chicken Fillet',price:34800,description:'Herb-marinated chicken fillet, char-grilled and served with ratatouille, mashed potatoes, and mustard mushroom sauce.'},
    {category:'Main Course',name:'Grilled Grouper',price:38600,description:'Delicate grilled grouper fish fillet, served with fragrant jasmine rice and a velvety, tangy coconut cream sauce.',tag:'NEW'},
    {category:'Main Course',name:'Grilled Jumbo Prawns',price:52200,description:'Succulent marinated jumbo prawns, served with crispy yam chips, fresh seasonal vegetables, and a silky martini sauce.'},
    {category:'Main Course',name:'Baked Salmon',price:54200,description:'Oven-roasted Norwegian salmon fillet, served alongside fresh spinach, tender edamame, and a smooth, flavorful martini sauce.'},
    {category:'Main Course',name:'Pan-Seared Seabass',price:54200,description:'Perfectly pan-seared seabass served with buttery mashed potatoes, sauteed spinach, and a fragrant lemongrass sauce.'},
    {category:'Meat Lovers',name:'Australian Ribeye',price:146200,description:'Grilled Australian ribeye steak served with roasted bone marrow and your choice of mushroom or pepper sauce.',tag:'NEW'},
    {category:'Meat Lovers',name:'Grilled Beef Tomahawk',price:118000,description:'Majestic premium imported tomahawk steak, grilled to perfection and served with sauteed onions, tender green beans, earthy mushrooms, roasted potato, and a rich pepper sauce.'},
    {category:'Meat Lovers',name:'Grilled T-Bone Steak',price:78400,description:'Juicy flame-grilled T-bone steak served with seasonal vegetables, mashed potatoes, and pepper sauce.'},
    {category:'Meat Lovers',name:'Steak Frites',price:58200,description:'Tender premium imported beef fillet, grilled to perfection, served with crisp, hand-cut skin-on fries and a velvety classic entrecote sauce.'},
    {category:'Meat Lovers',name:'Slow-Braised Lamb Shank',price:76200,description:'Tender slow-braised lamb shank served with green beans, creamy mashed potatoes, and pepper sauce.'},
    {category:'Meat Lovers',name:'Oxtail',price:89200,description:'Succulent slow-cooked oxtail, braised for 24 hours in its own rich juices, served with a flavorful oxtail broth, tender diced seasonal vegetables, and a creamy mashed potato.'},
    {category:'Meat Lovers',name:'Beef Ribs',price:83000,description:'Grilled beef ribs, cooked to perfection served with home made skin-on fries.',tag:'NEW'},
    {category:'Meat Lovers',name:'Flame-Grilled Pork Ribs',price:74200,description:'Flame-grilled pork ribs glazed with barbecue sauce, served with fries.'},
    {category:'Meat Lovers',name:'Grilled Lamb Chops',price:78400,description:'Grilled lamb chops served with vegetables, jollof rice, and pepper sauce.'},
    {category:'Dessert',name:'Strawberry Cheesecake',price:16800,description:'Biscuit and cream cheese topped with strawberry.'},
    {category:'Dessert',name:'Ice Cream Cake',price:16800,description:'Marbled ice cream layers with caramel and chocolate sauce.'},
    {category:'Dessert',name:'Sticky Date',price:16800,description:'Warm homemade date cake with caramel sauce, served with vanilla ice cream and fresh strawberries.',tag:'NEW'},
    {category:'Dessert',name:'Strawberry Crumble',price:16800,description:'Buttery pie crust filled with strawberry compote, topped with oat crumble. Served warm with vanilla ice cream and fresh strawberries.',tag:'NEW'},
    {category:'Dessert',name:'Banana Split',price:18000,description:''},
    {category:'Dessert',name:'Ice Cream Scoop',price:6000,description:'Single scoop of ice cream.'}
  ],
  refreshmentMenu: [
    {category:'Refreshments',name:'Soft Drinks',price:3800,description:''},
    {category:'Refreshments',name:'Water',price:3500,description:''},
    {category:'Refreshments',name:'Perrier 0.3L',price:6800,description:''},
    {category:'Refreshments',name:'Red Bull',price:7500,description:''},
    {category:'Refreshments',name:'Soda',price:3800,description:''},
    {category:'Refreshments',name:'Tonic',price:3800,description:''},
    {category:'Refreshments',name:'Bitter Lemon',price:3800,description:''}
  ]
};
